import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    dashboard: 'Dashboard',
    attendance: 'Attendance',
    families: 'Families',
    staff: 'Staff',
    timeTracking: 'Time Tracking',
    calendar: 'Calendar',
    settings: 'Settings',
    notes: 'Daily Notes',
    myshifts: 'My Shifts',
    mydocs: 'My Docs',
    photos: 'Photos',
    profile: 'Profile',
    shiftrequests: 'Shift Requests',
    staffschedule: 'Staff Schedule',
    announcements: 'Announcements',
    logout: 'Logout',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    date: 'Date',
    time: 'Time',
    reason: 'Reason',
    status: 'Status',
    confirmed: 'Confirmed',
    pending: 'Pending',
    vacation: 'Vacation',
    sick: 'Sick',
    doctor: 'Doctor Appointment',
    personal: 'Personal',
    other: 'Other',
    fullDay: 'Full Day',
    halfMorning: 'Half Day - Morning',
    halfAfternoon: 'Half Day - Afternoon',
    custom: 'Custom',
    clockIn: 'Clock In',
    clockOut: 'Clock Out',
    actualShift: 'Actual Shift',
    plannedShift: 'Planned Shift',
    uploadPhoto: 'Upload Photo',
    tagChildren: 'Tag Children',
    download: 'Download',
    noPhotos: 'No photos found',
    noEvents: 'No events scheduled',
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    upcomingBirthdays: 'Upcoming Birthdays',
    viewAll: 'View All',
    childrenPresent: 'Children Present',
    childrenAbsent: 'Children Absent',
    staffChildRatio: 'Staff:Child Ratio',
    allStaff: 'All Staff',
    clockedIn: 'Clocked In',
    addStaff: 'Add Staff Member',
    editStaff: 'Edit Staff Profile',
    fullName: 'Full Name',
    confirmDelete: 'Are you sure you want to delete this?',
    reactivate: 'Reactivate',
    suspend: 'Suspend',
    pendingShiftsCount: 'Pending Shift Requests',
    unmarkedAlert: 'Unmarked Children Alert',
    review: 'Review',
    attendanceProgress: 'Attendance Progress',
    userAccounts: 'User Accounts',
    manageLogins: 'Manage logins for staff and parents.',
    addUserAccount: 'Add User Account',
    editUser: 'Edit User',
    createNewUser: 'Create New User',
    fullNameReq: 'Full Name *',
    emailUsernameReq: 'Email / Username *',
    passwordReq: 'Password *',
    passwordHint: 'Password (leave blank to keep current)',
    rolePortalReq: 'Role / Portal *',
    updateAccount: 'Update Account',
    createAccount: 'Create Account',
    saving: 'Saving...',
    failedToSave: 'Failed to save user.',
    userUpdated: 'User updated successfully',
    userCreated: 'User created successfully',
    userDeleted: 'User deleted successfully',
    confirmDeleteUser: 'Are you sure you want to delete this user?',
    newNote: 'New Note',
    selectChild: 'Select Child',
    writeNotePrompt: 'Write note here (e.g. Ate all lunch, slept for 2 hours...)',
    saveNote: 'Save Note',
    recentNotes: 'Recent Notes',
    noteSaved: 'Note saved!',
    failedToSaveNote: 'Failed to save note',
    absenceReason: 'Absence Reason',
    lateArrivalReason: 'Late Arrival Reason',
    selectReason: 'Select Reason...',
    markAllPresent: 'Mark All Present',
    markAllAbsent: 'Mark All Absent',
    refresh: 'Refresh',
    noStaffMatching: 'No staff matching criteria.',
    clockInCaps: 'CLOCKED IN',
    verifyTimesheet: 'Verify Timesheet',
    timesheetVerified: 'Timesheet verified successfully',
    errorVerifying: 'Error verifying timesheet',
    familiesManagement: 'Families Management',
    addFamily: 'Add Family',
    editFamily: 'Edit Family',
    familyName: 'Family Name',
    mother: 'Mother',
    father: 'Father',
    emergency: 'Emergency',
    addChild: 'Add Child',
    dob: 'Date of Birth',
    allergies: 'Allergies',
    medicalInfo: 'Medical Info',
    deleteFamilyConfirm: 'Are you sure you want to delete this family and all linked records?',
    deleteChildConfirm: 'Delete this child profile?',
    noFamiliesFound: 'No families found. Add one to start.',
    saveChild: 'Save Child',
    saveFamily: 'Save Family',
    childName: "Child's Name",
    motherPhone: "Mother's Phone",
    fatherPhone: "Father's Phone",
    emergencyName: "Emergency Contact Name",
    emergencyPhone: "Emergency Contact Phone",
    reports: 'Reports',
    reminders: 'Reminders',
    emergencyContacts: 'Emergency',
    staffIn: 'Staff In',
    photoTitle: 'Photo Title',
    errorLoadingPhotos: 'Failed to load photos',
    photoUploaded: 'Photo uploaded successfully',
    uploadFailed: 'Upload failed',
    photoDeleted: 'Photo deleted',
    deleteFailed: 'Delete failed',
    noEntries: 'No entries yet',
    writeQuickNotes: 'Write quick daily notes for children.',
    userManagementDesc: 'Manage Staff and Parent accounts, assign roles, and suspend users.',
    goToUserManagement: 'Go to User Management',
    languageSection: 'Language Section',
    languageDesc: 'Choose the application language. Hebrew will automatically switch the layout to RTL.',
    dataMigration: 'Data Migration',
    dataMigrationDesc: 'Import or export all daycare data as .JSON.',
    importData: 'Import Data',
    exportData: 'Export Data',
    overview: 'Overview',
    quickReminders: 'Quick Reminders',
    quickActions: 'Quick Actions',
    childrenNeedAttendance: 'children unmarked',
    centerDocs: 'Center Documents',
    centerDocsDesc: 'Upload policy guides, forms, and manuals for parents or staff.',
    distributeNewDoc: 'Distribute New Document',
    docRepository: 'Document Repository',
    fileNameHint: 'File Name (e.g. Employee Handbook 2024)',
    categoryHint: 'Category (Policy, Medical Form, etc)',
    visibility: 'Visibility',
    publicVisibility: 'Public / All Users (Staff & Parents)',
    staffOnlyVisibility: 'Staff Only Database',
    uploadAndDistribute: 'Upload & Distribute',
    noFilesUploaded: 'No files uploaded yet.',
    restrictedStaff: 'Restricted (Staff)',
    visibleToAll: 'Visible to All',
    privateTo: 'Private to',
    photo: 'Photo',
    selectPhoto: 'Select Photo',
    confirmMarkAll: 'Confirm Bulk Action',
    confirmMarkAllMsg: 'Are you sure you want to mark all children as {{status}} for today?',
    yesMarkAll: 'Yes, Mark All',
    invalidFile: 'Invalid file format',
    dataImported: 'Data imported successfully! Reloading...',
  },
  he: {
    dashboard: 'לוח בקרה',
    attendance: 'נוכחות',
    families: 'משפחות',
    staff: 'צוות',
    timeTracking: 'מעקב שעות',
    calendar: 'יומן',
    settings: 'הגדרות',
    notes: 'הערות יומיות',
    myshifts: 'המשמרות שלי',
    mydocs: 'המסמכים שלי',
    photos: 'תמונות',
    profile: 'פרופיל',
    shiftrequests: 'בקשות משמרת',
    staffschedule: 'לוח זמנים לצוות',
    announcements: 'הודעות',
    logout: 'התנתק',
    save: 'שמור',
    cancel: 'ביטול',
    delete: 'מחק',
    edit: 'ערוך',
    add: 'הוסף',
    date: 'תאריך',
    time: 'שעה',
    reason: 'סיבה',
    status: 'סטטוס',
    confirmed: 'מאושר',
    pending: 'ממתין',
    vacation: 'חופשה',
    sick: 'מחלה',
    doctor: 'תור לרופא',
    personal: 'אישי',
    other: 'אחר',
    fullDay: 'יום פתוח (07:45-17:00)',
    halfMorning: 'חצי יום - בוקר (07:34-13:00)',
    halfAfternoon: 'חצי יום - צהריים (12:30-17:00)',
    custom: 'מותאם אישית',
    clockIn: 'כניסה',
    clockOut: 'יציאה',
    actualShift: 'משמרת בפועל',
    plannedShift: 'משמרת מתוכננת',
    uploadPhoto: 'העלאת תמונה',
    tagChildren: 'תיוג ילדים',
    download: 'הורדה',
    noPhotos: 'לא נמצאו תמונות',
    noEvents: 'אין אירועים מתוכננים',
    goodMorning: 'בוקר טוב',
    goodAfternoon: 'צהריים טובים',
    goodEvening: 'ערב טוב',
    upcomingBirthdays: 'ימי הולדת קרובים',
    viewAll: 'צפה בהכל',
    childrenPresent: 'ילדים נוכחים',
    childrenAbsent: 'ילדים נעדרים',
    staffChildRatio: 'יחס צוות:ילדים',
    allStaff: 'כל הצוות',
    clockedIn: 'נמצאים במשמרת',
    addStaff: 'הוסף איש צוות',
    editStaff: 'ערוך פרופיל איש צוות',
    fullName: 'שם מלא',
    confirmDelete: 'האם אתה בטוח שברצונך למחוק?',
    reactivate: 'הפעל מחדש',
    suspend: 'השעה',
    pendingShiftsCount: 'בקשות משמרת ממתינות',
    unmarkedAlert: 'התראת ילדים ללא נוכחות',
    review: 'סקירה',
    attendanceProgress: 'התקדמות נוכחות',
    userAccounts: 'חשבונות משתמשים',
    manageLogins: 'ניהול פרטי התחברות לצוות ולהורים.',
    addUserAccount: 'הוסף חשבון משתמש',
    editUser: 'ערוך משתמש',
    createNewUser: 'צור משתמש חדש',
    fullNameReq: 'שם מלא *',
    emailUsernameReq: 'אימייל / שם משתמש *',
    passwordReq: 'סיסמה *',
    passwordHint: 'סיסמה (השאר ריק כדי לשמור על הנוכחית)',
    rolePortalReq: 'תפקיד / פורטל *',
    updateAccount: 'עדכן חשבון',
    createAccount: 'צור חשבון',
    saving: 'שומר...',
    failedToSave: 'נכשל בשמירת המשתמש.',
    userUpdated: 'המשתמש עודכן בהצלחה',
    userCreated: 'המשתמש נוצר בהצלחה',
    userDeleted: 'המשתמש נמחק בהצלחה',
    confirmDeleteUser: 'האם אתה בטוח שברצונך למחוק משתמש זה?',
    newNote: 'הערה חדשה',
    selectChild: 'בחר ילד',
    writeNotePrompt: 'כתוב הערה כאן (למשל: אכל הכל, ישן שעתייים...)',
    saveNote: 'שמור הערה',
    recentNotes: 'הערות אחרונות',
    noteSaved: 'ההערה נשמרה!',
    failedToSaveNote: 'נכשל בשמירת ההערה',
    absenceReason: 'סיבת היעדרות',
    lateArrivalReason: 'סיבת איחור',
    selectReason: 'בחר סיבה...',
    markAllPresent: 'סמן את כולם כנוכחים',
    markAllAbsent: 'סמן את כולם כנעדרים',
    refresh: 'רענן',
    noStaffMatching: 'אין אנשי צוות תואמים.',
    clockInCaps: 'נמצא במשמרת',
    verifyTimesheet: 'אשר דיווח שעות',
    timesheetVerified: 'דיווח השעות אושר בהצלחה',
    errorVerifying: 'שגיאה באישור דיווח השעות',
    familiesManagement: 'ניהול משפחות',
    addFamily: 'הוסף משפחה',
    editFamily: 'ערוך משפחה',
    familyName: 'שם משפחה',
    mother: 'אמא',
    father: 'אבא',
    emergency: 'חירום',
    addChild: 'הוסף ילד',
    dob: 'תאריך לידה',
    allergies: 'אלרגיות',
    medicalInfo: 'מידע רפואי',
    deleteFamilyConfirm: 'האם אתה בטוח שברצונך למחוק משפחה זו וכל הרשומות המקושרות אליה?',
    deleteChildConfirm: 'האם למחוק את פרופיל הילד?',
    noFamiliesFound: 'לא נמצאו משפחות. הוסף אחת כדי להתחיל.',
    saveChild: 'שמור ילד',
    saveFamily: 'שמור משפחה',
    childName: 'שם הילד',
    motherPhone: 'טלפון אמא',
    fatherPhone: 'טלפון אבא',
    emergencyName: 'שם איש קשר לחירום',
    emergencyPhone: 'טלפון לחירום',
    reports: 'דוחות',
    reminders: 'תזכורות',
    emergencyContacts: 'חירום',
    staffIn: 'צוות במשמרת',
    photoTitle: 'כותרת תמונה',
    errorLoadingPhotos: 'נכשל בטעינת תמונות',
    photoUploaded: 'התמונה הועלתה בהצלחה',
    uploadFailed: 'ההעלאה נכשלה',
    photoDeleted: 'התמונה נמחקה',
    deleteFailed: 'המחיקה נכשלה',
    noEntries: 'אין רשומות עדיין',
    writeQuickNotes: 'כתוב הערות יומיות מהירות לילדים.',
    userManagementDesc: 'ניהול חשבונות צוות והורים, הקצאת תפקידים והשעיית משתמשים.',
    goToUserManagement: 'עבור לניהול משתמשים',
    languageSection: 'אזור שפה',
    languageDesc: 'בחר את שפת האפליקציה. מעבר לעברית ישנה את כיוון התצוגה לימין-לשמאל.',
    dataMigration: 'העברת נתונים',
    dataMigrationDesc: 'ייבוא או ייצוא כל נתוני הפעוטון כקובץ JSON.',
    importData: 'ייבוא נתונים',
    exportData: 'ייצוא נתונים',
    overview: 'סקירה כללית',
    quickReminders: 'תזכורות מהירות',
    quickActions: 'פעולות מהירות',
    childrenNeedAttendance: 'ילדים ללא סימון',
    centerDocs: 'מסמכי המרכז',
    centerDocsDesc: 'העלאת מדריכי מדיניות, טפסים ומדריכים להורים או לצוות.',
    distributeNewDoc: 'הפצת מסמך חדש',
    docRepository: 'מאגר מסמכים',
    fileNameHint: 'שם הקובץ (למשל: מדריך לעובד 2024)',
    categoryHint: 'קטגוריה (מדיניות, טופס רפואי וכו\')',
    visibility: 'נראות',
    publicVisibility: 'ציבורי / כל המשתמשים (צוות והורים)',
    staffOnlyVisibility: 'מאגר לצוות בלבד',
    uploadAndDistribute: 'העלה והפץ',
    noFilesUploaded: 'טרם הועלו קבצים.',
    restrictedStaff: 'מוגבל (צוות)',
    visibleToAll: 'גלוי לכולם',
    privateTo: 'פרטי עבור',
    photo: 'תמונה',
    selectPhoto: 'בחר תמונה',
    confirmMarkAll: 'אישור פעולה גורפת',
    confirmMarkAllMsg: 'האם אתה בטוח שברצונך לסמן את כל הילדים כ-{{status}} להיום?',
    yesMarkAll: 'כן, סמן את כולם',
    invalidFile: 'פורמט קובץ לא תקין',
    dataImported: 'הנתונים יובאו בהצלחה! מרענן...',
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('appLang') || 'en');

  useEffect(() => {
    localStorage.setItem('appLang', lang);
    document.documentElement.dir = lang === 'he' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => translations[lang]?.[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
