import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    dashboard: 'Dashboard',
    attendance: 'Attendance',
    families: 'Families',
    staff: 'Staff',
    timeTracking: 'Time Tracking',
    calendar: 'Calendar',
    settings: 'Settings',
    notes: 'Daily Notes',
    myshifts: 'My Shifts',
    mydocs: 'My Docs',
    photos: 'Photos',
    profile: 'Profile',
    shiftrequests: 'Shift Requests',
    staffschedule: 'Staff Schedule',
    announcements: 'Announcements',
    logout: 'Logout',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    date: 'Date',
    time: 'Time',
    reason: 'Reason',
    status: 'Status',
    confirmed: 'Confirmed',
    pending: 'Pending',
    vacation: 'Vacation',
    sick: 'Sick',
    doctor: 'Doctor Appointment',
    personal: 'Personal',
    other: 'Other',
    fullDay: 'Full Day',
    halfMorning: 'Half Day - Morning',
    halfAfternoon: 'Half Day - Afternoon',
    custom: 'Custom',
    clockIn: 'Clock In',
    clockOut: 'Clock Out',
    actualShift: 'Actual Shift',
    plannedShift: 'Planned Shift',
    uploadPhoto: 'Upload Photo',
    tagChildren: 'Tag Children',
    download: 'Download',
    noPhotos: 'No photos found',
    noEvents: 'No events scheduled',
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    upcomingBirthdays: 'Upcoming Birthdays',
    viewAll: 'View All',
    childrenPresent: 'Children Present',
    childrenAbsent: 'Children Absent',
    staffChildRatio: 'Staff:Child Ratio',
    allStaff: 'All Staff',
    clockedIn: 'Clocked In',
    addStaff: 'Add Staff Member',
    editStaff: 'Edit Staff Profile',
    fullName: 'Full Name',
    confirmDelete: 'Are you sure you want to delete this?',
    reactivate: 'Reactivate',
    suspend: 'Suspend',
    pendingShiftsCount: 'Pending Shift Requests',
    unmarkedAlert: 'Unmarked Children Alert',
    review: 'Review',
    attendanceProgress: 'Attendance Progress',
  },
  he: {
    dashboard: 'לוח בקרה',
    attendance: 'נוכחות',
    families: 'משפחות',
    staff: 'צוות',
    timeTracking: 'מעקב שעות',
    calendar: 'יומן',
    settings: 'הגדרות',
    notes: 'הערות יומיות',
    myshifts: 'המשמרות שלי',
    mydocs: 'המשמכים שלי',
    photos: 'תמונות',
    profile: 'פרופיל',
    shiftrequests: 'בקשות משמרת',
    staffschedule: 'לוח זמנים לצוות',
    announcements: 'הודעות',
    logout: 'התנתק',
    save: 'שמור',
    cancel: 'ביטול',
    delete: 'מחק',
    edit: 'ערוך',
    add: 'הוסף',
    date: 'תאריך',
    time: 'שעה',
    reason: 'סיבה',
    status: 'סטטוס',
    confirmed: 'מאושר',
    pending: 'ממתין',
    vacation: 'חופשה',
    sick: 'מחלה',
    doctor: 'תור לרופא',
    personal: 'אישי',
    other: 'אחר',
    fullDay: 'יום מלא',
    halfMorning: 'חצי יום - בוקר',
    halfAfternoon: 'חצי יום - צהריים',
    custom: 'מותאם אישית',
    clockIn: 'כניסה',
    clockOut: 'יציאה',
    actualShift: 'משמרת בפועל',
    plannedShift: 'משמרת מתוכננת',
    uploadPhoto: 'העלאת תמונה',
    tagChildren: 'תיוג ילדים',
    download: 'הורדה',
    noPhotos: 'לא נמצאו תמונות',
    noEvents: 'אין אירועים מתוכננים',
    goodMorning: 'בוקר טוב',
    goodAfternoon: 'צהריים טובים',
    goodEvening: 'ערב טוב',
    upcomingBirthdays: 'ימי הולדת קרובים',
    viewAll: 'צפה בהכל',
    childrenPresent: 'ילדים נוכחים',
    childrenAbsent: 'ילדים נעדרים',
    staffChildRatio: 'יחס צוות:לבטל',
    allStaff: 'כל הצוות',
    clockedIn: 'נמצאים במשמרת',
    addStaff: 'הוסף איש צוות',
    editStaff: 'ערוך פרופיל איש צוות',
    fullName: 'שם מלא',
    confirmDelete: 'האם אתה בטוח שברצונך למחוק?',
    reactivate: 'הפעל מחדש',
    suspend: 'השעה',
    pendingShiftsCount: 'בקשות משמרת ממתינות',
    unmarkedAlert: 'התראת ילדים ללא נוכחות',
    review: 'סקירה',
    attendanceProgress: 'התקדמות נוכחות',
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('appLang') || 'en');

  useEffect(() => {
    localStorage.setItem('appLang', lang);
    document.documentElement.dir = lang === 'he' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => translations[lang]?.[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
